src/objects/Boat__c.object
<CustomObject>
    <label>Boat</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BoatReview__c.object
<CustomObject>
    <fields>
        <fullName>Boat__c</fullName>
        <label>Boat</label>
        <referenceTo>Boat__c</referenceTo>
        <relationshipLabel>Boat Reviews</relationshipLabel>
        <relationshipName>Boat_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BoatReview</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BoatReviewsController.cls
public with sharing class BoatReviewsController
{
    @AuraEnabled
    public static List<BoatReview__c>  getAll(String boatTypeId)
    {
        List<BoatReview__c> reviewList = new List<BoatReview__c>();
        
        reviewList = [SELECT Id, Comment__c,Rating__c,CreatedBy.Id,CreatedBy.Name,
                      CreatedBy.SmallPhotoUrl,CreatedBy.CompanyName,LastModifiedDate,CreatedDate 
                      FROM BoatReview__c 
                      WHERE Boat__c =: boatTypeId];
                      
        //return review list
        
        return reviewList;              
    }
}