src/objects/Boat__c.object
<CustomObject>
    <fields>
        <fullName>BoatType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Boat Type</label>
        <referenceTo>BoatType__c</referenceTo>
        <relationshipLabel>Boats</relationshipLabel>
        <relationshipName>Boats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Boats</relationshipLabel>
        <relationshipName>Boats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <type>Url</type>
    </fields>
    <label>Boat</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BoatType__c.object
<CustomObject>
    <label>Boat Type</label>
    <nameField>
        <label>Boat Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BoatSearchResults.cls
public class BoatSearchResults
{
  
    @AuraEnabled
    public static Boat__c[]  getBoats(String boatTypeId)
    {
        if(boatTypeId !='foo') {
        
            Boat__c[] boatList = new Boat__c[]{};
            
            boatList = [SELECT id, BoatType__c, picture__c, name,contact__r.Name
                    FROM Boat__c
                    WHERE BoatType__c =:boatTypeId LIMIT 10];
            
            //return boats
            return boatList;        
        }else {
          
            Boat__c[] allboatList = new Boat__c[]{};
            //return a list of all boats
            allboatList = [SELECT id, BoatType__c, picture__c, name,contact__r.Name
                    FROM Boat__c LIMIT 10];
                    
            return allboatList;        
        }
    }
}