src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment to be Serviced</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Lifespan_Months__c</fullName>
        <label>Lifespan Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Replacement_Part__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Replacement Part</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Warehouse_SKU__c</fullName>
        <externalId>true</externalId>
        <label>Warehouse SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>VIN_Number__c</fullName>
        <label>VIN Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactoryOld.cls
@IsTest
public class TestDataFactoryOld {

    public static List<Case> createMaintenanceRequest(string Type, integer howmany) {

        List<Case> MRList = new List<Case>();

        if (howmany >0 && Type != null ){
            //create Veichle
            Vehicle__c v = new Vehicle__c(Name='TestVehicle', VIN_Number__c='asdfgf424');
            insert v;

            //create multiple equipments
            List<Product2> equips = new List<Product2>();
            equips.add(new Product2(Name='TestEquipment1', Warehouse_SKU__c='1111111', Lifespan_Months__c=6, Maintenance_Cycle__c=30, Replacement_Part__c=true));
            equips.add(new Product2(Name='TestEquipment2', Warehouse_SKU__c='9999999', Lifespan_Months__c=12, Maintenance_Cycle__c=30, Replacement_Part__c=true));
            equips.add(new Product2(Name='TestEquipment3', Warehouse_SKU__c='5555555', Lifespan_Months__c=18, Maintenance_Cycle__c=60, Replacement_Part__c=true));
            equips.add(new Product2(Name='TestEquipment4', Warehouse_SKU__c='4444444', Lifespan_Months__c=24, Maintenance_Cycle__c=90, Replacement_Part__c=true));
            insert equips; 

            //create maintenance requests
            for (integer i = 0; i<howmany; i++) {
                MRList.add(new Case(Type = Type, Status='New', Origin='Phone', Equipment__c=equips[0].id, Subject='Test Maintenance Request'));
            }
            insert MRList;

            //create work parts for maintenance requests
            List<Work_Part__c> wpList = new List<Work_Part__c>();
            for (Case c: MRList) {
                wpList.add(new Work_Part__c(Equipment__c=equips[0].id, Maintenance_Request__c=c.id, Quantity__c=1));
                wpList.add(new Work_Part__c(Equipment__c=equips[1].id, Maintenance_Request__c=c.id, Quantity__c=2));
            }
            insert wpList;

        }   

        return MRList;
    }
}