src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Inventory__c</fullName>
        <label>Current Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifespan_Months__c</fullName>
        <label>Lifespan Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Replacement_Part__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Replacement Part</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Warehouse_SKU__c</fullName>
        <externalId>true</externalId>
        <label>Warehouse SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WarehouseCalloutService.cls
public with sharing class WarehouseCalloutService {

    private static final String WAREHOUSE_URL = 'https://th-superbadge-apex.herokuapp.com/equipment';
    
    // complete this method to make the callout (using @future) to the
    // REST endpoint and update equipment on hand.
    @future(callout=true)
    public static void runWarehouseEquipmentSync(){
    
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(WAREHOUSE_URL);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        
        if (response.getStatusCode() == 200) {
          
            List<Object> warehouseequipments = (List<Object>) JSON.deserializeUntyped(response.getBody());
            List<Product2> equipments = new List<Product2>();
            for(Object WE :  warehouseequipments){
                Map<String, Object> equipmentMap = (Map<String, Object>)WE;
                
                Product2 equipment = new Product2();
                equipment.Name = (String)equipmentMap.get('name');
                equipment.Cost__c = (Integer)equipmentMap.get('cost');
                equipment.Current_Inventory__c = (Integer)equipmentMap.get('quantity');
                equipment.Maintenance_Cycle__c = (Integer)equipmentMap.get('maintenanceperiod');
                equipment.Replacement_Part__c = (Boolean)equipmentMap.get('replacement');
                equipment.Lifespan_Months__c = (Integer)equipmentMap.get('lifespan');
                equipment.Warehouse_SKU__c = (String)equipmentMap.get('sku');
                equipment.ProductCode = (String)equipmentMap.get('_id');
                equipments.add(equipment);
            }
            if(equipments.size() > 0){
                System.debug('EQUIPMENTS::::'+equipments);
                upsert equipments;
            }
        }
    }

}